version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: opticsmanager_mysql
    environment:
      MYSQL_ROOT_PASSWORD: manal
      MYSQL_DATABASE: opticsmanagerdb
    ports:
      - "3307:3306"  # Use 3307 to avoid conflict with your local MySQL
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      start_period: 30s

  app:
    build: .
    container_name: opticsmanager_app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/opticsmanagerdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge